### ISSUE TITLE
use lastchange date from nodes.json

### ISSUE THREAD

**Issue by LeSpocky** [FreifunkMD/community.json#1]
At the moment api.js sets the time of execution as lastchange timestamp. This would be okay if the nodes.json were always a current one. However in case of problems it would be better to use the lastchange timestamp from nodes.json itself, which would reflect the actual lastchange.

**Comment by bastinat0r** [comment]
Normally the lastchange field is for the update of the api itself, if you aggregate data from multiple sources tracking those will be very complex (wheras this method is not).
